"""export_neo4j_table.py — render a Cypher result as a semio LaTeX table fragment.

The counterpart to `render_neo4j_diagram.py`: some relationships are numbers, not
shapes. A two-source fan-in like "how many Bauteilgruppen and Projekte carry each
Hürde" produces an unreadable node-link diagram but a clear table, and tables are
already part of the semio print identity (`print/tex/semio-table.sty`).

Emits a `.tex` fragment using the package's public two-column API — `\\SemioTableTwo`,
`\\SemioTableHeaderRow`, `\\SemioTableRow` — inside a `Table` window, so it carries the
same hairline frame, title tab and register entry as every other window.

    python _scripts/export_neo4j_table.py --table huerden-traeger
    python _scripts/export_neo4j_table.py --list

Queries must return a `left` and a `right` column. Read-only by contract, same guard
as the diagram renderer. Identity rules: .claude/skills/semio-styling/SKILL.md
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
_SCRIPTS = _REPO / "_scripts"
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from neo4j_env import resolve_connection  # noqa: E402
from neo4j_to_dot import UnsafeQueryError, assert_read_only  # noqa: E402

TABLES_PATH = _REPO / "_neo4j" / "diagrams" / "tables.json"
DEFAULT_OUT_DIR = _REPO / "_neo4j" / "exports" / "diagrams"

#: LaTeX specials that must survive a German caption unescaped.
_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def tex_escape(value) -> str:
    return "".join(_ESCAPES.get(ch, ch) for ch in str(value))


def load_tables(path: Path = TABLES_PATH) -> dict[str, dict]:
    if not path.is_file():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    return {entry["name"]: entry for entry in data.get("tables", [])}


def fetch_rows(cypher: str, params: dict | None, database: str) -> list[tuple[str, str]]:
    """Run `cypher` and return (left, right) pairs."""
    assert_read_only(cypher)
    from neo4j import GraphDatabase

    uri, user, password, default_db = resolve_connection()
    driver = GraphDatabase.driver(uri, auth=(user, password))
    rows: list[tuple[str, str]] = []
    try:
        driver.verify_connectivity()
        with driver.session(database=database or default_db, default_access_mode="READ") as session:
            for record in session.run(cypher, params or {}):
                row = dict(record)
                if "left" not in row or "right" not in row:
                    raise ValueError(
                        f"Table queries must return 'left' and 'right' columns; got {sorted(row)}."
                    )
                rows.append((str(row["left"]), str(row["right"])))
    finally:
        driver.close()
    return rows


def build_tex(entry: dict, rows: list[tuple[str, str]]) -> str:
    """A `Table` window wrapping the package's two-column table."""
    title = tex_escape(entry.get("title", entry["name"]))
    headers = entry.get("headers", ["", ""])
    body = [
        "  \\SemioTableHeaderRow{%s & %s}"
        % (tex_escape(headers[0]), tex_escape(headers[1]))
    ]
    for left, right in rows:
        body.append("  \\SemioTableRow{%s & %s}" % (tex_escape(left), tex_escape(right)))

    lines = [
        "% Generated by _scripts/export_neo4j_table.py — do not edit by hand.",
        f"% source: {entry['name']} · regenerate after any graph change.",
        f"\\begin{{Table}}[title={title}]",
        "  \\SemioTableTwo{%",
        "\n".join(body),
        "  }",
        "\\end{Table}",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    source = ap.add_mutually_exclusive_group()
    source.add_argument("--table", help="Name of a table from _neo4j/diagrams/tables.json")
    source.add_argument("--all", action="store_true", help="Export every table")
    source.add_argument("--list", action="store_true", help="List the catalogue and exit")
    ap.add_argument("--database", help="Override the configured database")
    ap.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    args = ap.parse_args()

    tables = load_tables()

    if args.list:
        if not tables:
            print(f"No table catalogue at {TABLES_PATH}")
            return 1
        print(f"{len(tables)} tables in {TABLES_PATH.relative_to(_REPO)}\n")
        for name, entry in tables.items():
            print(f"  {name:<24} {entry.get('description', '')}")
        return 0

    if args.all:
        targets = list(tables.values())
    elif args.table:
        if args.table not in tables:
            print(f"Unknown table {args.table!r}. Known: {', '.join(tables) or '(none)'}",
                  file=sys.stderr)
            return 1
        targets = [tables[args.table]]
    else:
        ap.error("choose one of --table, --all or --list")

    _, _, _, default_db = resolve_connection()
    database = args.database or default_db
    args.out_dir.mkdir(parents=True, exist_ok=True)

    failures = 0
    for entry in targets:
        try:
            rows = fetch_rows(entry["cypher"], entry.get("params"), database)
        except (UnsafeQueryError, ValueError) as exc:
            print(f"FAIL [{entry['name']}]: {exc}", file=sys.stderr)
            failures += 1
            continue
        except Exception as exc:
            print(f"FAIL [{entry['name']}]: {type(exc).__name__}: {exc}", file=sys.stderr)
            failures += 1
            continue

        out = args.out_dir / f"{entry['name']}.tex"
        out.write_text(build_tex(entry, rows), encoding="utf-8")
        print(f"OK  {entry['name']:<24} {len(rows):>3} rows  {out.name} ({out.stat().st_size:,} B)")

    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
