"""Generate the semio TikZ token file from the single source of truth.

Emits `_neo4j/diagrams/tikz/semio-tikz-tokens.tex` — xcolor definitions and
stroke/type macros for the semio TikZ style package. Every value is resolved
through `semio_style.py`, so a TikZ diagram that uses these names is guaranteed
to match the Graphviz output and pass `validate_semio_styling.py`.

Re-run after any token change (it is part of the styling gate, like
`sync_semio_tokens.py`). Never hand-edit the generated .tex.

Usage:
  python _scripts/gen_semio_tikz_tokens.py            # write the file
  python _scripts/gen_semio_tikz_tokens.py --check    # fail if stale (CI/gate)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from semio_style import (  # noqa: E402
    SEMIO,
    paint_for_emphasis,
    print_pt,
    tokens_digest,
)

OUT = _SCRIPTS.parent / "_neo4j" / "diagrams" / "tikz" / "semio-tikz-tokens.tex"


def _hex(value: str) -> str:
    return value.lstrip("#").upper()


def build() -> str:
    normal = paint_for_emphasis("normal")
    focus = paint_for_emphasis("focus")
    # Semantic paints — all token-derived, all in allowed_colors().
    colors = {
        "semionodefill": normal.fill,          # board.nodeFill  #EEEADB
        "semionodestroke": normal.border,      # board.nodeStroke #7B827D
        "semionodefont": normal.font_color,    # contrast text    #001117
        "semionodechip": normal.chip_color,    # muted chip        #6B736F
        "semiofocusfill": focus.fill,          # nodeFillSelected  #FF344F
        "semiofocusstroke": focus.border,      # nodeStrokeSelected
        "semiofocusfont": focus.font_color,
        "semiofocuschip": focus.chip_color,
        "semioedgestroke": SEMIO.board("edgeStroke"),
        "semiocanvas": SEMIO.chrome("canvas"),      # register fill   #F0ECDD
        "semiopanel": SEMIO.chrome("panel"),        # register tab    #C9C8BD
        "semiobase": SEMIO.chrome("base"),          # sheet surface   #F7F3E3
        "semioforeground": SEMIO.chrome("foreground"),   # #001117
        "semiomuted": SEMIO.chrome("mutedForeground"),   # #7B827D
        "semioaccent": SEMIO.chrome("accent"),           # #FF344F
    }
    strokes = {
        "semiohairline": print_pt("stroke@hairline"),
        "semiodefaultstroke": print_pt("stroke@default"),
        "semiofocuswidth": print_pt("stroke@focus"),
    }
    sizes = {
        "semiobodysize": print_pt("chrome@font@body"),
        "semiochipsize": print_pt("chrome@font@chip"),
    }

    lines = [
        "% semio-tikz-tokens.tex — GENERATED by _scripts/gen_semio_tikz_tokens.py",
        "% Do NOT edit by hand. Values resolve from _neo4j/diagrams/semio/tokens.json",
        f"% token digest: {tokens_digest()}",
        "\\RequirePackage{xcolor}",
        "",
        "% -- semio paints (state, never kind; every hex is a semio token) --",
    ]
    for name, value in colors.items():
        lines.append(f"\\definecolor{{{name}}}{{HTML}}{{{_hex(value)}}}")
    lines.append("")
    lines.append("% -- print strokes (pt, not screen px) --")
    for name, value in strokes.items():
        lines.append(f"\\newcommand{{\\{name}}}{{{value}pt}}")
    lines.append("")
    lines.append("% -- type sizes (pt) --")
    for name, value in sizes.items():
        lines.append(f"\\newcommand{{\\{name}}}{{{value}pt}}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="Exit 1 if the generated file is missing or stale")
    args = ap.parse_args()

    content = build()
    if args.check:
        if not OUT.is_file() or OUT.read_text(encoding="utf-8") != content:
            print(f"STALE: {OUT} does not match semio tokens — run "
                  f"python _scripts/gen_semio_tikz_tokens.py", file=sys.stderr)
            return 1
        print(f"OK: {OUT.name} matches semio tokens")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(_SCRIPTS.parent)} ({len(content.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
