# 🔠 Rollengruppen der Klassifikations-Taxonomie (Abschnitte A--O). Die
# gedruckte Tabelle zeigt den Gruppenbuchstaben statt der ausgeschriebenen
# Rolle: 93 verschiedene Rollen kommen vor, ausgeschrieben passen sie nicht
# neben die Relevanz in 181 mm. `Referenzprojekt` (Regel P, Bauvorhaben)
# steht ausserhalb der Taxonomieabschnitte und bildet die Gruppe P.
# Abgeleitet aus KLASSIFIKATION_TAXONOMIE.md, nicht von Hand gepflegt.
ROLE_GROUPS = {
    'A': ('Eigentum, Bauherrschaft, Finanzierung', (
        'Bauherrschaft',
        'Beschaffung',
        'Finanzierung',
        'Fördermittelvergabe',
        'Gebäudeeigentum',
        'Investor',
        'Portfoliomanagement',
        'Programmmanagement',
        'Projektentwicklung',
        'Projektsteuerung',
        'Versicherung',
        'Öffentliche Beschaffung',
    )),
    'B': ('Regulierung und Recht', (
        'Genehmigung und Aufsicht',
        'Politikberatung',
        'Rechtsberatung',
        'Regulierung',
        'Reuse-Beratung',
        'Reuse-Strategie',
        'Vertragsgestaltung',
    )),
    'C': ('Planung und Gestaltung', (
        'Architektur',
        'Ausschreibung und Vergabe',
        'Ausstellungs- und Veranstaltungsbau',
        'Bauphysik',
        'Beschaffungsplanung',
        'Bestandsentwicklung',
        'Brandschutzplanung',
        'Demontagegerechtes Design',
        'Gebäudetechnikplanung',
        'Innenarchitektur',
        'Kostenplanung',
        'Landschaftsarchitektur',
        'Logistikplanung',
        'Materialberatung',
        'Möbeldesign',
        'Produktdesign',
        'Reuse-Planung',
        'Rückbauplanung',
        'Schadstoffplanung',
        'Stadt- und Arealplanung',
        'Technische Planung',
        'Tragwerksplanung',
        'Umnutzungsplanung',
    )),
    'D': ('Inventarisierung und Suche', (
        'Bauteilinventarisierung',
        'Bauteilsuche',
        'Bestandsaufnahme',
        'Digitale Bestandserfassung',
        'Material- und Bauteilbeschaffung',
        'Potenzialbewertung',
        'Reuse-Audit',
    )),
    'E': ('Prüfung und Qualität', (
        'Brandschutzprüfung',
        'Funktionsprüfung',
        'Herkunftsnachweis',
        'Materialprüfung',
        'Qualitätsprüfung',
        'Qualitätssicherung',
        'Risikobewertung',
        'Rückverfolgbarkeit',
        'Schadstoffprüfung',
        'Technische Prüfung',
        'Tragfähigkeitsprüfung',
        'Umweltbewertung',
        'Wertermittlung',
        'Wirtschaftlichkeitsbewertung',
        'Zertifizierung',
        'Zulassung und Normenkonformität',
        'Zustandsbewertung',
    )),
    'F': ('Rückbau und Bergung', (
        'Bergung',
        'Demontage',
        'Rücknahme',
        'Rücknahmesystem',
        'Schadstoffsanierung',
        'Selektiver Rückbau',
        'Sortierung',
    )),
    'G': ('Aufarbeitung', (
        'Anpassung',
        'Aufarbeitung',
        'Ersatzteilversorgung',
        'Fertigung mit Reuse-Material',
        'Instandhaltung',
        'Modernisierung',
        'Reinigung',
        'Reparatur',
        'Sanierung',
        'Umnutzung',
        'Werkstattfertigung',
        'Wiederaufbereitung',
    )),
    'H': ('Lagerung und Logistik', (
        'Baustellenlogistik',
        'Lagerung',
        'Rückführungslogistik',
        'Transport',
        'Verpackung und Schutz',
        'Zwischenlagerung',
    )),
    'I': ('Handel und Vermittlung', (
        'Auktion',
        'Bauteilhandel',
        'Leasing',
        'Produkt-Service-System',
        'Vermietung',
        'Vermittlung',
        'Vermittlungsplattform',
        'Weitergabe',
    )),
    'J': ('Bauausführung', (
        'Bauausführung',
        'Baustellenkoordination',
        'Generalunternehmung',
        'Montage',
        'Systemintegration',
        'Wiedereinbau',
    )),
    'K': ('Betrieb und Nutzung', (
        'Facility Management',
        'Gebäudebetrieb',
        'Modulare Systeme',
        'Nutzungsmanagement',
        'Temporärnutzung',
    )),
    'L': ('Daten und Infrastruktur', (
        'BIM und digitaler Zwilling',
        'Bauteilkataster',
        'Bestandsdatenmanagement',
        'Bilderkennung',
        'Datenanalyse',
        'Datenplattform',
        'Datenstandardisierung',
        'Materialdokumentation',
        'Materialpass',
        'Softwareentwicklung',
    )),
    'M': ('Methoden und Erprobung', (
        'Angewandte Forschung',
        'Methodenentwicklung',
        'Monitoring und Evaluation',
        'Pilotierung',
        'Technologieentwicklung',
    )),
    'N': ('Bildung und Vernetzung', (
        'Ausbildung',
        'Berufliche Qualifizierung',
        'Branchenverband',
        'Community-Aufbau',
        'Interessenvertretung',
        'Lehre',
        'Netzwerkkoordination',
        'Normung',
        'Richtlinienentwicklung',
        'Standardisierung',
        'Veranstaltungsorganisation',
        'Weiterbildung',
        'Wissenstransfer',
        'Wissensvermittlung',
        'Öffentlichkeitsarbeit',
    )),
    'O': ('Soziale Zusatzfunktion', (
        'Arbeitsintegration',
        'Beschäftigungsprogramm',
        'Soziale Qualifizierung',
    )),
    'P': ('Referenzprojekt', ('Referenzprojekt', 'Referenzprojekt, Reuse-Umfang unklar')),
}

ROLE_GROUP = {r: k for k, (_, rs) in ROLE_GROUPS.items() for r in rs}
GROUP_LABEL = {k: label for k, (label, _) in ROLE_GROUPS.items()}
